# Generated by Django 3.1.1 on 2020-09-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('head0', models.CharField(default=50, max_length=500)),
                ('chead0', models.CharField(default='', max_length=5000)),
                ('head1', models.IntegerField(default=0, max_length=500)),
                ('chead1', models.CharField(max_length=5000)),
                ('head2', models.CharField(max_length=500)),
                ('chead2', models.CharField(max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
