# Generated by Django 3.1 on 2020-08-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200821_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pricr',
            new_name='price',
        ),
    ]
