# Generated by Django 3.1.1 on 2020-09-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='name',
            field=models.CharField(default='', max_length=90),
        ),
    ]
