# Generated by Django 3.1.1 on 2020-09-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderupdate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='name',
        ),
    ]
