# Generated by Django 3.1.2 on 2020-10-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20201029_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item2',
            new_name='Product2',
        ),
    ]
