# Generated by Django 3.1.2 on 2020-10-29 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20201029_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product2',
            old_name='i_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='subtotal',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order2',
            name='discount',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='order2',
            name='subtotal',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='order2',
            name='total',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='product2',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product2',
            name='descripton',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product2',
            name='marked_price',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='product2',
            name='selling_price',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='product2',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='product2',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
