# Generated by Django 3.1.7 on 2021-04-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_product_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='marked_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='return_policy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
    ]
