# Generated by Django 3.1.7 on 2021-04-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210414_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marked_price',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(default='its is good for daily use', max_length=300),
        ),
        migrations.AlterField(
            model_name='product2',
            name='marked_price',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='product2',
            name='selling_price',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
